filter:
  excluded_paths:
    - vendor/*
    - spec/*

tools:
  php_analyzer:
    filter:
      excluded_paths:
        - spec/*

  php_mess_detector: true

  php_code_sniffer:
    filter:
      excluded_paths:
        - spec/*
    config:
      standard: PSR2

  php_sim:
    filter:
      excluded_paths:
        - spec/*

    sensiolabs_security_checker: true

    php_pdepend: true

    php_loc:
      enabled: true
      excluded_dirs: [vendor]

    php_cpd:
      enabled: true
      excluded_dirs: [vendor]